chore: Generate continuous changelog
wireapp/wire-account pull request #2307
Opened 2020-12-16 12:46 UTC by Yserz

2020-12-16 14:32 UTC, lipis approved these changes

2020-12-17 09:56 UTC, ffflorian approved these changes

2020-12-17 09:56 UTC, ffflorian commented on bin/changelog.js
> +  /** This contains just the changelog of the last release.
```suggestion
  /**
    * This contains just the changelog of the last release.
```

2020-12-17 09:56 UTC, ffflorian requested changes
Tests are breaking

2023-05-12 19:55 UTC, ffflorian commented
😄

2025-01-03 16:51 UTC, closed without merging